### ISSUE TITLE
cant initialize properly

### ISSUE THREAD

**Issue by 123maxmix123** [totaljs/node-paypal-express-checkout#18]
**I'm trying to do exatly the ame thing, in readme file.
But when add** 

paypal.init(......)

**my server tells me:** 

paypal.pay('20130001', 123.23, 'iPad', 'EUR', true, function(err, url) {
				       ^

TypeError: paypal.pay is not a function
    at Namespace.<anonymous> (/var/www/html/NewProject/working_node/quiz/app.js:121:12)
    at emitOne (events.js:77:13)
    at Namespace.emit (events.js:169:7)
    at Namespace.emit (/var/www/html/NewProject/working_node/quiz/node_modules/socket.io/lib/namespace.js:206:10)
    at /var/www/html/NewProject/working_node/quiz/node_modules/socket.io/lib/namespace.js:174:14
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

Any help?
I saw index.js and it seems correct, but i cant figure out why i get this error

**Comment by molda** [comment]
Sorry I made a mistake when i updated readme.
Use this, notice Upper case P in Paypal
```
var Paypal = require('paypal-express-checkout');
paypal = Paypal.init(...);
paypal.pay(...);
```

**Comment by 123maxmix123** [comment]
Ok, now works :)
One more question regarding token.
I never understood good enough how paypal works, anyway how do i get the token from paypal rest api through the code?
Maybe i should indicate right return address?
